# Generated by Django 3.2.8 on 2021-10-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_buyerdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Seller', 'Seller'), ('Buyer', 'Buyer'), ('Viewer', 'Viewer'), ('Deliverer', 'Deliverer')], default='Viewer', max_length=120),
        ),
    ]
