# Generated by Django 3.2.8 on 2021-10-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
        ('payment', '0002_auto_20211022_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='product',
        ),
        migrations.AddField(
            model_name='delivery',
            name='product',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
