# Generated by Django 3.2.8 on 2021-10-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20211022_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='product',
        ),
        migrations.AddField(
            model_name='delivery',
            name='purchases',
            field=models.ManyToManyField(to='payment.Purchase'),
        ),
    ]
