# Generated by Django 3.2.8 on 2021-10-17 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('business_name', models.CharField(blank=True, max_length=120, null=True)),
                ('business_address', models.CharField(blank=True, max_length=120, null=True)),
                ('ein_number', models.CharField(blank=True, max_length=120, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=120, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=120, null=True)),
                ('bank_routing_number', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('voided_check_or_direct_deposit_form', models.FileField(blank=True, null=True, upload_to='')),
                ('credit_line', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('cash_line_of_credit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('total_line_of_credit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
