# Generated by Django 3.2.8 on 2021-10-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bank_routing_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cash_line_of_credit',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='credit_line',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ein_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_line_of_credit',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='voided_check_or_direct_deposit_form',
        ),
    ]
